title: Usable Fonts
description: Desc...
lang: en
author: menozero

repository: menozero/usable-fonts
github_username: menozero

# theme: minima
remote_theme: jekyll/minima

plugins:
- jekyll-remote-theme

minima:
  skin: solarired
  
